### ISSUE TITLE
Thread border router

### ISSUE THREAD

**Issue by jonsmirl** [Xinyuan-LilyGO/T-ZigBee#1]
This hardware is capable of being a Thread border router. Are you working on the software for doing that?

**Comment by liangyingy** [comment]
The original factory does not provide thread sdk. There is no plan to develop a thread for the time being.

http://wiki.telink-semi.cn/wiki/chip-series/TLSR825x-Series/

![image](https://user-images.githubusercontent.com/46518962/165656886-7e52c89b-5192-4638-91b2-81e17e1060c4.png)

**Comment by jonsmirl** [comment]
Their datasheet says they have it:
http://wiki.telink-semi.cn/doc/ds/PB_TLSR8258-E_Product%20Brief%20for%20Telink%20BLE%20IEEE802.15.4%20Multi-Standard%20Wireless%20SoC%20TLSR8258.pdf

6LoWPAN and Thread features
 Supports 6LowPAN, IPv6 and DHCPv6
 Supports UDP and DTLS
 Supports thread security and commission

So it should be coming

**Comment by jonsmirl** [comment]
The Thread implementation may be inside the HomeKit support.

**Comment by liangyingy** [comment]
The HomeKit sdk of tlsr8258 is based on ble.

**Comment by jcomas** [comment]
Here http://wiki.telink-semi.cn/wiki/protocols/Zigbee/ you find Zigbee SDK. Then, you can use the modifications from https://github.com/pvvx/TlsrComSwireWriter to upload a new firmware in TLSR8258.

**Comment by liangyingy** [comment]
> Can you tell me more about the included Zigbee firmware? Maybe, it is a similar to "tl_zigbee_sdk\apps\sampleGw" from Zigbee SDK. I'm interested in comunicate ESP via UART to TLSR8258 using HCI (zbhci.h), but I'd like TLSR8258 as Zigbee enddevice.

You can refer to [light_demo](https://github.com/Xinyuan-LilyGO/T-ZigBee/tree/main/examples/light_demo).
