### ISSUE TITLE
New sensor demo application with dht sensor

### ISSUE THREAD

**Issue by swkim01** [Xinyuan-LilyGO/T-ZigBee#11]
Hello,

I added new sensor demo application in my repository. You can test it with a dht11/22 sensor. Enjoy!
[https://github.com/swkim01/T-ZigBee/tree/main/examples/sensor_demo](https://github.com/swkim01/T-ZigBee/tree/main/examples/sensor_demo)

**Comment by liangyingy** [comment]
great! Welcome to submit PR!

**Comment by liangyingy** [comment]
#12

**Comment by pawilli** [comment]
> Hello,
> 
> I added new sensor demo application in my repository. You can test it with a dht11/22 sensor. Enjoy! https://github.com/swkim01/T-ZigBee/tree/main/examples/sensor_demo

Hi @swkim01.  

Thank you for working on the sensory demo.  I have a DS18B20 and can get it to work using on this board using ESPhome but the esphome implementation is unstable and I would prefer to pick up the temperature through your zigbee-based program.  

How can I change the DHT in the example you provided to a DS18B20?

Thanks
