### ISSUE TITLE
What is the wire and connector at the back for?

### ISSUE THREAD

**Issue by pawilli** [Xinyuan-LilyGO/T-ZigBee#18]
Hello,

What is the red and black wire and connector at the back for?  From the schematic is seems to suggest a battery connection.  If that is the case what is the voltage?

Thanks

![connector](https://user-images.githubusercontent.com/106495221/204793894-e380e839-cb09-407e-b01f-0f366975a9c4.jpg)

![61fuaI02F2L _AC_SX679_](https://user-images.githubusercontent.com/106495221/204793935-dabd2088-3913-4bcc-8eca-7a9105e9455f.jpg)

**Comment by lbuque** [comment]
It can be used to connect a 4.2V lithium battery.
