### ISSUE TITLE
Schematics and source code firmware

### ISSUE THREAD

**Issue by jcomas** [Xinyuan-LilyGO/T-ZigBee#2]
Hello!

Could you provide to us the schematics of T-Zigbee board and the source code of firmware loaded in TLSR8258 chip?

Regards,
    Josep

**Comment by liangyingy** [comment]
schematics: https://github.com/Xinyuan-LilyGO/T-ZigBee/blob/main/Schematic/T-Zigbee.pdf

**Comment by liangyingy** [comment]
TLSR8258 SDK: https://github.com/Xinyuan-LilyGO/telink-zigbee-sdk
